config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :items do
    member do
      patch 'order_item'
    end
    collection do
      get 'order_bulk' 
    end
  end

  resources :activities, only: :index

  resources :orders, only: [:show, :index, :new] do
    collection do
      get 'bulk_order'
      get 'total_amount'
      get 'order_detail'
    end
  end

  root 'items#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/reference_id.rb
require 'active_support/concern'

module ReferenceId
  extend ActiveSupport::Concern

  included do

    def self.referenced_with(options={})
      length = options[:length] || 6
      prefix = options[:prefix]
      prefix_length = prefix.length
      length_of_reference_id = length - prefix_length

      define_method(:reference_id) do
        "#{prefix}%0#{length_of_reference_id}d" % "#{id}"
      end
    end

  end

end

app/models/item.rb
class Item < ApplicationRecord

  include ReferenceId
  include PublicActivity::Common

  referenced_with prefix: :IN

  validates_presence_of :name,
            :product_model_number

  validates :quantity, 
            :unit_value,
            presence: true,
            numericality: true

  before_save :write_value!
  
  has_many :orders
  belongs_to :user

  scope :find_required_items, ->(item_ids){where(id: item_ids)}

  accepts_nested_attributes_for :orders

  def evaluate_total_sum(quantity, percentage)
    evaluate_item_price(quantity) + evaluate_gst_price(percentage, quantity)
  end

  class << self

    def create_bulk_order(params, current_user, current_time)
      ActiveRecord::Base.transaction do
        params.each do |key, value|
          item = current_user.items.find(value[:item_id])
          order = item.orders.build(value)
          order.user_id = current_user.id
          order.placed_at_uts = current_time
          order.save
        end
      end
    end

  end

  private

  def write_value!
    self.value = calculate_item_value
  end

  def calculate_item_value
    calculate_item_price + calculate_gst_price
  end

  def calculate_item_price
    unit_value * quantity
  end

  def calculate_gst_price
    (unit_value*gst_percentage/100) * quantity
  end

  def evaluate_item_price(quantity)
    unit_value * quantity
  end

  def evaluate_gst_price(percentage, quantity)
    (unit_value*percentage/100) * quantity
  end

end

app/models/order.rb
class Order < ApplicationRecord

  include ReferenceId

  include PublicActivity::Common

  attr_accessor :_destroy

  referenced_with prefix: :ON

  belongs_to :item
  belongs_to :user

  after_save :write_item_attribute!

  validate :order_quantity, :order_amount

  delegate :name, :product_model_number, :unit_value,:vendor_url, :location, to: :item, allow_nil: true

  scope :placed_orders, ->(placed_time){ where(placed_at_uts: placed_time) }

  private

  def write_item_attribute!
    item.value = calcualte_remaing_amount
    item.quantity = calcualte_remaing_quantity
    item.save(validates: false)
  end

  def calcualte_remaing_amount
    item.value - amount
  end

  def calcualte_remaing_quantity
    (item.quantity - quantity)
  end

  def order_quantity
    if quantity.blank? || quantity > item.quantity || quantity == 0
      errors.add(:base, :invalid)
    end
  end

  def order_amount
    if amount.blank? || amount > item.value || amount == 0
      errors.add(:base, :invalid)
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :orders
   has_many :items

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = PublicActivity::Activity
      .where(owner_id: current_user.id, owner_type: 'User')
      .order("created_at desc")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :valid_request


  private

  def valid_request
    if unpermitted_request
      redirect_to new_user_session_path
    end
  end

  def unpermitted_request
    puts controller_name
    controller_name ==  'registrations'
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :find_item, only: [:edit, :update, :show, :order_item]
  before_action :find_items, only: :order_bulk

  def index
    @search = current_user.items.ransack(params[:q])
    @item = @search.result
  end

  def new
    @item = current_user.items.new
  end

  def create
    @item = current_user.items.new(item_params)
    if @item.save
      @item.create_activity :create, owner: current_user
      flash[:notice] = 'item created sucessfully'
      redirect_to items_path
    else
      flash[:alert] = 'item not created'
      redirect_to new_item_path
    end
  end

  def update
    if @item.update_attributes(item_params)
      flash[:notice] = 'item updated sucessfully'
      redirect_to items_path
    else
      flash[:alert] = 'item not updated sucessfully'
      redirect_to items_path
    end
  end

  def order_item
    @order = @item.orders.build(build_attributes)
    @order.user_id = current_user.id
    if @order.save
      flash[:notice] = 'order placed sucessfully'
      @order.create_activity :order_item, owner: current_user
      redirect_to order_path(@order)
    else
      flash[:alert] = 'Order quantity should not be zero or less than item quantity'
      redirect_to item_path
    end
  end

  def order_bulk
    count1 = Order.count
    current_time = Time.now.to_i
    @items.create_bulk_order(params[:item][:orders_attributes], current_user, current_time)
    count2 = Order.count
    if count2 > count1
      flash[:notice] = 'order placed sucessfully'
      redirect_to order_detail_orders_path(current_time: current_time)
    else
      flash[:alert] = 'Order quantity should not be zero or less than item quantity'
      redirect_to new_order_path
    end
  end

  private

  def item_params
    params.require(:item).permit!
  end

  def find_item
    @item = current_user.items.find(params[:id])
  end

  def build_attributes
    { quantity: params[:item][:quantity], amount: params[:item][:value], gst_percentage: params[:item] [:gst_percentage] }
  end

  def find_items
    @item_ids = []
    params[:item][:orders_attributes].each do |key, value|
      @item_ids << "#{value['item_id']}"
    end
    @items = current_user.items.find_required_items(@item_ids)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @search = current_user.orders.ransack(params[:q])
    @order = @search.result
  end

  def show
    @order = Order.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'receipt',
        template: 'orders/show.html.slim'
      end
    end
  end

  def total_amount
    @item = Item.find(params[:item_id])
    @amount = @item.evaluate_total_sum(params[:quantity].to_f, params[:percentage].to_f)
      respond_to do |format|
      format.json { render json: @amount.to_json }
    end
  end

  def order_detail
    @orders = Order.placed_orders(params[:current_time].to_i)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'receipt',
        template: 'orders/order_detail.html.slim'
      end
    end
  end

  def new
    @item = Item.first
    @orders = @item.orders.build
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_pdf_request?
    params[:format] == 'pdf'
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/activities/index.html.slim
.row.pull-right
  .col-md-12
    .row
      .table-responsive
        table.table.table-bordered.table-striped
          thead
            tr
              th data-sortable='true' = t('.notifications')
          tbody
            - @activities.each do |activity|
              tr
                td
                  = link_to activity.owner.email, '#' if activity.owner
                  = render_activity activity
                

app/views/items/_form.html.slim
.col-md-10.col-md-offset-1
  = bootstrap_form_for @item, layout: :horizontal,
     label_col: 'col-md-3', control_col: 'col-md-7' do |f|
    = f.text_field :name, help: t('.name_of_the_item')
    = f.text_field :product_model_number, help: t('.product_model_number')
    = f.text_field :quantity, help: t('.quantity')
    = f.text_field :unit_value, help: t('.unit_value')
    = f.text_field :gst_percentage, help: t('.gst_percentage')
    = f.text_field :vendor_url, help: t('.vendor')
    = f.text_field :location, help: t('.location')
    = f.form_group
      .pull-right
        = link_to t('buttons.cancel'), items_path,
            class: 'btn btn-danger btn-sm'
        |&nbsp;
        = f.submit t('buttons.save'), data: { confirm: t('.are_you_sure_you_want_to_add_item')}, class: 'btn btn-success btn-sm'
  .space-20

app/views/items/edit.html.slim
.space-20
h4.text-center = t('.edit_item')
=render 'form'

app/views/items/index.html.slim
.space-20
h4.text-center = t('.items_in_inventory')
.row
  .col-md-12
    .table-wrapper
      .row
        .col-md-7
          = render partial: 'shared/search'
        .col-md-5
          .pull-right
            = link_to t('.add_new_item'), new_item_path, class: 'btn btn-success'
      .space-20
        .table-responsive
          table.table.table-bordered.table-striped#bootstrap-table
            thead
              tr
                th data-sortable='true' = t('.reference_id')
                th data-sortable='true' = t('.item_name')
                th data-sortable='true' = t('.model_name')
                th data-sortable='true' = t('.quantity')
                th data-sortable='true' = t('.unit_value')
                th data-sortable='true' = t('.gst_percentage')
                th data-sortable='true' = t('.total_value')
                th data-sortable='true' = t('.vendor')
                th data-sortable='true' = t('.location')
                th = t('general.action')
            tbody
              - @item.each do |item|
                tr
                  td = item.reference_id
                  td = link_to item.name, item_path(item)
                  td = item.product_model_number
                  td = item.quantity
                  td = item.unit_value
                  td = item.gst_percentage
                  td = item.value
                  td = item.vendor_url
                  td = item.location
                  td
                    = link_to '', edit_item_path(item),
                      class: "glyphicon glyphicon-pencil"

app/views/items/new.html.slim
.space-20
h4.text-center = t('.new_item')
=render 'form'

app/views/items/show.html.slim
space-20
h4.text-center = "Item Detail of Order"
.space-20
  = bootstrap_form_for @item, url: order_item_item_path, validate: true do |f|
    .col-md-9.col-md-offset-1.col-xs-8.col-xs-offset-1
      .row
        label.col-md-5.control-label = t('.reference_id')
        label.col-md-4 = f.object.reference_id
      .row
        label.col-md-5.control-label = t('.name')
        label.col-md-4 = f.object.name
      .row
        label.col-md-5.control-label = t('.model_name')
        label.col-md-4 = f.object.product_model_number
      .row
        label.col-md-5.control-label Updated On:
        label.col-md-4
          = f.object.try(:updated_at).try(:to_s, :dd_month_yyyy_at_hh_mm)
          = f.hidden_field :unit_value, id: :unit_value
      .row
        label.col-md-5.control-label = t('.unit_value')
        label.col-md-4 = f.object.unit_value
      .row
        label.col-md-5.control-label = t('quantity')
        label.col-md-4
          = f.text_field :quantity, hide_label: true, class: 'form-control'
      .row
        label.col-md-5.control-label = t('.gst_percentage')
        label.col-md-4
          = f.text_field :gst_percentage, hide_label: true
      .row
        label.col-md-5.control-label Cost:
        label.col-md-4
          = f.text_field :value,  hide_label: true, disabled: true, class: 'form-control'
          = f.hidden_field :value, class: 'hidden_value'
      .space-20
        .row
          .pull-right
            = link_to 'cancel', items_path,
                class: 'btn btn-danger btn-sm'
            |&nbsp;
            = f.submit 'Order', data: { confirm: t('.are_you_sure_you_want_to_place_the_order') }, class: 'btn btn-success btn-sm'

app/views/layouts/_navigation.html.slim
nav.main-nav.navbar.navbar-default role='navigation'
  .container
    .navbar-header
      button.navbar-toggle data-target='#navbar-collapse' data-toggle='collapse' type='button'
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    #navbar-collapse.navbar-collapse.collapse
       = render_navigation level: 1..2, expand_all: true, renderer: :bootstrap

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | GstInventory
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header.header
      .top-bar
        .container
          .col-md-1.header-logo
            .col-md-2
              = image_tag 'logo.png', alt: 'logo'
          - if user_signed_in?
            .pull-right
              ul.nav.navbar-nav
                li
                  = link_to image_tag('logout_logo.png'), destroy_user_session_path, method: :delete,
                    data: { confirm: 'Are you sure you want to logout?' }, class: 'icon btn'
          - else
            .pull-right
              ul.nav.navbar-nav
                li
                  = link_to image_tag('login_logo.png'), new_user_session_path, class: 'icon btn'
      - if user_signed_in?
          = render partial: 'layouts/navigation'
    .page-content
      .container
        - if notice
          p.alert.alert-success
            = notice
        - if alert
          p.alert.alert-danger
            = alert
        = yield
  .footer.space-20
    .container.no-padding
      .col-md-6.no-padding.col-xs-7.col-sm-8
        small.copyright Copyright © AMTECH #{Time.now.year}, All Rights Reserved
      .pull-right
        span GstInventory

app/views/orders/_order_fields.html.slim
.nested-fields
  .panel.panel-default
    .panel-body
      = f.collection_select :item_id, current_user.items, :id, :name, {},
        { class: 'chosen-select item_id' }
      = f.text_field :customer_name
      = f.select :payment_mode, ['CASH PAYMENT', 'CHECK PAYMENT', 'CREDIT' ]
      = f.text_field :quantity, class: 'quantity'
      = f.text_field :gst_percentage, class: 'gst-percentage'
      = f.text_field :amount, disabled: true, class: 'amount'
      = f.hidden_field :amount, class: 'hide-amount'
    .links.pull-right
      = link_to_remove_association '', f, class: 'glyphicon glyphicon-trash'
javascript:
  $('.gst-percentage').on('change', function() {
    var element = this;
    var quantity = $(element).closest('.form-group').prev().find('.quantity').val()
    var item_id = $(element).closest('.form-group').prev().prev().prev().prev().find('.item_id').val()
    $.ajax({
      url: 'total_amount',
      data: { quantity: quantity, item_id: item_id, percentage: $(this).val() },
      success: function(response){
        $(element).closest('.form-group').next().find('.amount').val(response)
        $(element).closest('.form-group').next().next().val(response)
      }
    });
  });

app/views/orders/_search.html.slim
.form-group
  = search_form_for @search, html: {class: 'form-horizontal'} do |f|
    .form-group
      .col-md-3
        = label_tag 'Date', nil, class: 'control-label'
        = f.text_field :created_at_gteq, class: 'datepicker'
      label.col-md-1 to
      .col-md-3
        = f.text_field :created_at_lteq, class: 'datepicker'
    .form-group
      = f.submit 'Submit', class: 'btn btn-success btn-sm'
      |&nbsp;
      = link_to 'Clear', orders_path, class: 'btn btn-success btn-sm'

app/views/orders/index.html.slim
.space-20
h4.text-center = t('.placed_orders')
.space-20
  = render partial: 'search'
.row
  .col-md-12
    .table-wrapper
      .space-20
        .table-responsive
          table.table.table-bordered.table-striped#bootstrap-table
            thead
              tr
                th data-sortable='true' = t('.reference_id')
                th data-sortable='true' = t('.item_name')
                th data-sortable='true' = t('.model_name')
                th data-sortable='true' = t('.quantity')
                th data-sortable='true' = t('.unit_value')
                th data-sortable='true' = t('.gst_percentage')
                th data-sortable='true' = t('.total_value')
                th data-sortable='true' = t('.vendor')
                th data-sortable='true' = t('.location')
                th data-sortable= 'true' = t('.ordered_on')
            tbody
              - @order.each do |order|
                tr
                  td = order.reference_id
                  td = link_to order.name, order_path(order)
                  td = order.product_model_number
                  td = order.quantity
                  td = order.unit_value
                  td = order.gst_percentage
                  td = order.amount
                  td = order.vendor_url
                  td = order.location
                  td = order.created_at

app/views/orders/new.html.slim
= javascript_include_tag 'order.js'
.col-md-10.col-md-offset-1
  = bootstrap_form_for @item, url: order_bulk_items_path, method: :get, layout: :horizontal,
     label_col: 'col-md-3', control_col: 'col-md-7' do |f|
    #orders
      = f.fields_for :orders, @orders do |order_details|
        = render 'order_fields', f: order_details
      .links.pull-right
        = link_to_add_association 'Add', f, :orders, class: 'btn btn-sm btn-success'
      = f.form_group
        .pull-right
          = link_to t('buttons.cancel'), items_path,
              class: 'btn btn-danger btn-sm'
          |&nbsp;
          = f.submit t('buttons.order'), data: { confirm: t('.are_you_sure_you_want_to_place_order')}, class: 'btn btn-success btn-sm'
    .space-20

app/views/orders/order_detail.html.slim
- if is_pdf_request?
  = wicked_pdf_stylesheet_link_tag 'application'
  = image_tag wicked_pdf_asset_base64('logo.png')
- @orders.each do |order|
  .panel.panel-default
    .panel-body
      .row.col-md-3.pull-right
        p
          strong = t('.address')
        p
          strong = 'Suman Agency Ram Janki Mandir Road Simdega, Mob No: 9835721967'
      .space-40
        .col-md-5
          p
            strong = "Item Detail of Order"
        .com-md-7
          p
            strong = 'GST NO 20ACDPA0117'
        .space-20
          .col-md-9.col-md-offset-1.col-xs-8.col-xs-offset-1
            .row
              label.col-md-5.control-label = t('.reference_id')
              label.col-md-4 = order.item.reference_id
            .row
              label.col-md-5.control-label = t('.customer_name')
              label.col-md-4 = order.customer_name
            .row
              label.col-md-5.control-label = t('.item_name')
              label.col-md-4 = order.item.name
            .row
              label.col-md-5.control-label = t('.model_name')
              label.col-md-4 = order.item.product_model_number
            .row
              label.col-md-5.control-label = t('.order_date')
              label.col-md-4
                = order.try(:updated_at).try(:to_s, :dd_month_yyyy_at_hh_mm)
            .row
              label.col-md-5.control-label = t('.unit_value')
              label.col-md-4 = order.item.unit_value
            .row
              label.col-md-5.control-label = t('quantity')
              label.col-md-4 = order.quantity
            .row
              label.col-md-5.control-label = t('.gst_percentage')
              label.col-md-4 = order.gst_percentage
            .row
              label.col-md-5.control-label Cost:
              label.col-md-4 = order.amount
            .row
              label.col-md-5.control-label = t('.payment_mode')
              label.col-md-4 = order.payment_mode
- if !is_pdf_request?
  .space-20
    .row
      = link_to t('.print'), order_detail_orders_path(format: :pdf, current_time: params[:current_time]), class: 'btn btn-success'
      |&nbsp;
      = link_to 'Back', orders_path, class: 'btn btn-warning'

app/views/orders/show.html.slim
- if is_pdf_request?
  = wicked_pdf_stylesheet_link_tag 'application'
  = image_tag wicked_pdf_asset_base64('logo.png')
.row.col-md-3.pull-right
  p
    strong = t('.address')
  p
    strong = 'Suman Agency Ram Janki Mandir Road Simdega, Mob No: 9835721967'
.space-40
  .col-md-5
    p
      strong = "Item Detail of Order"
  .com-md-7
    p
      strong = 'GST NO 20ACDPA0117'
  .space-20
    .col-md-9.col-md-offset-1.col-xs-8.col-xs-offset-1
      .row
        label.col-md-5.control-label = t('.reference_id')
        label.col-md-4 = @order.item.reference_id
      .row
        label.col-md-5.control-label = t('.item_name')
        label.col-md-4 = @order.item.name
      .row
        label.col-md-5.control-label = t('.model_name')
        label.col-md-4 = @order.item.product_model_number
      .row
        label.col-md-5.control-label = t('.order_date')
        label.col-md-4
          = @order.try(:updated_at).try(:to_s, :dd_month_yyyy_at_hh_mm)
      .row
        label.col-md-5.control-label = t('.unit_value')
        label.col-md-4 = @order.item.unit_value
      .row
        label.col-md-5.control-label = t('quantity')
        label.col-md-4 = @order.quantity
      .row
        label.col-md-5.control-label = t('.gst_percentage')
        label.col-md-4 = @order.gst_percentage
      .row
        label.col-md-5.control-label Cost:
        label.col-md-4 = @order.amount
      - if !is_pdf_request?
        .space-20
          .row
            = link_to t('.print'), order_path(@order, format: :pdf), class: 'btn btn-success'
            |&nbsp;
            = link_to 'Back', orders_path, class: 'btn btn-warning'

app/views/public_activity/index.html.erb
added a recipe

<% if activity.trackable %>
  <%= link_to activity.trackable.name, activity.trackable %>
<% else %>
  which has since been removed
<% end %>

app/views/public_activity/item/_create.html.slim
p = t('.added_a_item')
- if activity.trackable
  = link_to activity.trackable.name, activity.trackable
- else
  which has since been removed

app/views/public_activity/order/_order_item.html.slim
p = t('.order_a_item')
- if activity.trackable
  = link_to activity.trackable.name, activity.trackable
- else
  which has since been removed

app/views/shared/_search.html.slim
.row
  .col-md-12
    = search_form_for @search, html: {class: 'form-horizontal'} do |f|
      .form-group
        = label_tag 'Item Name', nil, class: 'col-md-2 control-label'
        .col-md-4
          = f.select :name_in,
            options_from_collection_for_select(current_user.items, :name,
            proc { |obj| obj.name },
            selected: params[:q] ? params[:q][:name_in] : nil),
            { include_blank: 'Select' }, { class: 'chosen-select form-control' }
      = f.submit 'Submit', class: 'btn btn-success btn-sm'
      |&nbsp;
      = link_to 'Clear', items_path, class: 'btn btn-success btn-sm'